# Generated by Django 5.0.7 on 2024-09-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='steet_address',
            new_name='street_address',
        ),
    ]
