# Generated by Django 5.0.7 on 2024-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
