# Generated by Django 5.0.7 on 2024-09-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_borrowbook_remove_book_user_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
