# Generated by Django 5.0.7 on 2024-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_borrowbook_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='book_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
