# Generated by Django 5.0.7 on 2024-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_bookcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_borrowed', models.BooleanField(default=False)),
                ('book_title', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.CharField(choices=[(1, 'Not too bad'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], max_length=20)),
            ],
        ),
    ]
