# Generated by Django 5.0.7 on 2024-09-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_userreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
