# Generated by Django 5.0.7 on 2024-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_rating_userreview_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user_rating',
            field=models.IntegerField(choices=[(1, 'Not too bad'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], max_length=20),
        ),
    ]
