# Generated by Django 5.0.7 on 2024-09-14 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_userreview_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='book_title',
        ),
        migrations.AddField(
            model_name='userreview',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.book'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
