# Generated by Django 5.0.7 on 2024-09-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_userreview_book_title_userreview_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
