# Generated by Django 5.0.7 on 2024-09-14 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_userreview_name'),
        ('useraccount', '0002_rename_steet_address_user_address_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.user_account'),
        ),
    ]
