# Generated by Django 5.0.7 on 2024-09-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_borrowbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.book'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
