# Generated by Django 5.0.7 on 2024-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_alter_userreview_book_alter_userreview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
