# Generated by Django 5.0.7 on 2024-09-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_userreview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.book'),
        ),
    ]
