# Generated by Django 5.0.7 on 2024-09-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_userreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user_rating',
            field=models.CharField(choices=[('Not too bad', 'Not too bad'), ('Average', 'Average'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], max_length=20, null=True),
        ),
    ]
