# Generated by Django 5.0.7 on 2024-09-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_userreview_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='is_borrowed',
        ),
    ]
