# Generated by Django 5.0.7 on 2024-09-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_remove_userreview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='userreview',
            name='user_rating',
        ),
    ]
