# Generated by Django 5.0.7 on 2024-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_remove_userreview_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='user_rating',
            field=models.CharField(choices=[('Not too bad', 'Not too bad'), ('Average', 'Average'), ('Good', 'Good'), ('Very Good', 'Very Good'), ('Excellent', 'Excellent')], max_length=20, null=True),
        ),
    ]
