# Generated by Django 5.0.7 on 2024-09-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_userreview_name_userreview_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
